### ISSUE TITLE
breaks with socket.io > 1.4

### ISSUE THREAD

**Issue by chrisid** [jbillmann/GarageServer.IO#28]
firts of all, I am loving your library, thanks for sharing this. 

I am using socket.io@1.3.7 and all is good.
but when updated to 1.4.4 it stops working, seems like a namespace issue

**Comment by Lyian** [comment]
Can confirm this bug! Since I will dig through the code, I will provide an fix here if I can update the library.

**Comment by jbillmann** [comment]
Thanks - I've been meaning to apply the latest 'round of updates.  I'll look to do so soon and keep you posted.

**Comment by Lyian** [comment]
Awesome, Thanks!
